# Navigation
menu:
  Home:
    url: //www.rainmeter.net/
    external: true
  Documentation:
    url: /
    external: false
  Discover:
    url: //rainmeter.net/discover
    external: true
  Community:
    url: //forum.rainmeter.net/
    external: true
